# Joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Effort controllers with PID for each joint (more stable in Gazebo)
joint_1_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 10.0, i: 0.0, d: 1.0}

joint_2_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 20.0, i: 0.0, d: 2.0}

joint_3_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_3
  pid: {p: 20.0, i: 0.0, d: 2.0}

joint_4_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_4
  pid: {p: 5.0, i: 0.0, d: 0.5}

joint_5_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_5
  pid: {p: 5.0, i: 0.0, d: 0.5}

joint_6_effort_controller:
  type: effort_controllers/JointPositionController
  joint: joint_6
  pid: {p: 5.0, i: 0.0, d: 0.5}
